/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Creator: SceneKit export preview 0.66
*/

import * as THREE from 'three'
import { useEffect, useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    planes: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_1_1: THREE.Mesh
    mesh_1_2: THREE.Mesh
    mesh_1_3: THREE.Mesh
    mesh_1_4: THREE.Mesh
    mesh_1_5: THREE.Mesh
    mesh_1_6: THREE.Mesh
    mesh_1_7: THREE.Mesh
    mesh_1_8: THREE.Mesh
    mesh_1_9: THREE.Mesh
    mesh_1_10: THREE.Mesh
    mesh_1_11: THREE.Mesh
    mesh_1_12: THREE.Mesh
    mesh_1_13: THREE.Mesh
    MeshTransform: THREE.Mesh
    MeshTransform_1: THREE.Mesh
    MeshTransform_2: THREE.Mesh
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
    Back_clayable_colorable: THREE.MeshStandardMaterial
    Black_clayable: THREE.MeshStandardMaterial
    Camera_Module_clayable_colorable: THREE.MeshStandardMaterial
    Edge_clayable_colorable: THREE.MeshStandardMaterial
    Edge_Antenna_clayable_colorable: THREE.MeshStandardMaterial
    Flash_clayable: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Glass_Screen: THREE.MeshStandardMaterial
    Gray_clayable: THREE.MeshStandardMaterial
    Lens_clayable: THREE.MeshStandardMaterial
    Back_Glass: THREE.MeshStandardMaterial
    Matte_clayable: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    Screen_Edge_clayable: THREE.MeshStandardMaterial
    Material_001: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    rotatoTag: THREE.MeshStandardMaterial
  }
}

type ModelProps = JSX.IntrinsicElements['group'] & {
  screenTextureUrl?: string
}

export function Model({ screenTextureUrl, ...props }: ModelProps) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(
    '/assets/models/Samsung_Galaxy_S21_Ultra_2021.glb'
  ) as GLTFResult

  const defaultScreenTexture = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 2640">
      <rect width="1200" height="2640" fill="#0f172a"/>
      <rect x="78" y="110" width="1044" height="2420" rx="62" fill="#111827"/>
      <circle cx="600" cy="1300" r="180" fill="#1e293b" opacity="0.9"/>
      <rect x="210" y="720" width="780" height="220" rx="18" fill="#cbd5e1" opacity="0.18"/>
      <rect x="220" y="1040" width="760" height="420" rx="22" fill="#ffffff" opacity="0.08"/>
      </svg>
  `)}`

  const screenTexture = useTexture(screenTextureUrl ?? defaultScreenTexture)

  useEffect(() => {
    if (!screenTexture) return

    screenTexture.colorSpace = THREE.SRGBColorSpace
   

    // if (materials.Screen) {
      materials.Screen.map = screenTexture
      materials.Screen.color.set('#fff')
      materials.Screen.emissive.set('#000000')
      materials.Screen.metalness = 0
      materials.Screen.envMapIntensity = 0
      materials.Screen.transparent = false
      materials.Screen.needsUpdate = true
      materials.Screen.roughness = 0
    // }

    // if (materials.Glass_Screen) {
    //   materials.Glass_Screen.map = null
    //   materials.Glass_Screen.visible = false
    //   materials.Glass_Screen.color.set('#ffffff')
    //   materials.Glass_Screen.emissive.set('#000000')
    //   materials.Glass_Screen.roughness = 1
    //   materials.Glass_Screen.metalness = 0
    //   materials.Glass_Screen.transparent = true
    //   materials.Glass_Screen.opacity = 0
    //   materials.Glass_Screen.depthWrite = false
    //   materials.Glass_Screen.needsUpdate = true
    // }
    // materials.Glass.map = null
  }, [materials, screenTexture])

  useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="PWA_Export_9C4408A8_1221_4F23_BECC_78D3A4CDE30D">
          <group name="Geom">
            <group name="Rig">
              <PerspectiveCamera
                name="CameraTransform"
                makeDefault={false}
                far={5000}
                near={0.001}
                fov={31.891}
              />
            </group>
            <group name="Device_Scene">
              <group name="Custom_Model">
                <group name="Devices">
                  <group name="Custom">
                    <group name="Device_0">
                      <group name="Device_0_1">
                        <group name="Device_0_2" scale={100}>
                          <group name="Geom_1">
                            <group name="Device">
                              <mesh
                                name="mesh_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1.geometry}
                                material={materials.Back_clayable_colorable}
                              />
                              <mesh
                                name="mesh_1_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_1.geometry}
                                material={materials.Black_clayable}
                              />
                              <mesh
                                name="mesh_1_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_2.geometry}
                                material={materials.Camera_Module_clayable_colorable}
                              />
                              <mesh
                                name="mesh_1_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_3.geometry}
                                material={materials.Edge_clayable_colorable}
                              />
                              <mesh
                                name="mesh_1_4"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_4.geometry}
                                material={materials.Edge_Antenna_clayable_colorable}
                              />
                              <mesh
                                name="mesh_1_5"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_5.geometry}
                                material={materials.Flash_clayable}
                              />
                              <mesh
                                name="mesh_1_6"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_6.geometry}
                                material={materials.Glass}
                              />
                              <mesh
                                name="mesh_1_7"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_7.geometry}
                                material={materials.Glass_Screen}
                              />
                              <mesh
                                name="mesh_1_8"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_8.geometry}
                                material={materials.Gray_clayable}
                              />
                              <mesh
                                name="mesh_1_9"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_9.geometry}
                                material={materials.Lens_clayable}
                              />
                              <mesh
                                name="mesh_1_10"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_10.geometry}
                                material={materials.Back_Glass}
                              />
                              <mesh
                                name="mesh_1_11"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_11.geometry}
                                material={materials.Matte_clayable}
                              />
                              <mesh
                                name="mesh_1_12"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_12.geometry}
                                material={materials.Screen}
                              />
                              <mesh
                                name="mesh_1_13"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_1_13.geometry}
                                material={materials.Screen_Edge_clayable}
                              />
                            </group>
                            <group name="Point_001" position={[0.169, 0.186, 0.063]} />
                            <group name="Point_002" position={[0, 0, 0.614]} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Cameras">
                  <PerspectiveCamera
                    name="CameraTransform_1"
                    makeDefault={false}
                    far={500}
                    near={0.1}
                    fov={30.676}
                    position={[0, 0, 29.642]}
                  />
                  <PerspectiveCamera
                    name="CameraTransform_2"
                    makeDefault={false}
                    far={500}
                    near={0.1}
                    fov={30.676}
                    position={[0, 1.498, 96.149]}
                    rotation={[0.127, 0.066, -0.008]}
                  />
                  <PerspectiveCamera
                    name="CameraTransform_3"
                    makeDefault={false}
                    far={500}
                    near={0.1}
                    fov={30.676}
                    position={[-4.907, 7.732, 8.082]}
                    rotation={[-0.116, -0.564, -0.065]}
                  />
                </group>
                <PerspectiveCamera
                  name="CameraTransform_4"
                  makeDefault={false}
                  far={100}
                  near={0.001}
                  fov={60}
                  position={[0, 17.069, 0.417]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                {/* <group name="lighting">
                  <group name="spot_top" position={[0, -0.231, 13.996]} rotation={[-1.608, 0, 0]} />
                  <group
                    name="spot_front"
                    position={[0, 16.459, 11.847]}
                    rotation={[-0.898, 0, 0]}
                  />
                  <group
                    name="spot_back"
                    position={[11.162, 16.459, -11.847]}
                    rotation={[-2.179, 0.502, -0.045]}
                  />
                  <group name="ambient" position={[0, 27.764, -0.587]} />
                </group> */}
              </group>
              <group name="Labels" />
            </group>
            <group name="reflection_probe" position={[0, 0.655, 0]} scale={100} />
            <PerspectiveCamera
              name="CameraTransform_5"
              makeDefault={false}
              far={500}
              near={0.2}
              fov={30.676}
              position={[0, 0, 28.756]}
            />
            <group name="resetViews">
              <PerspectiveCamera
                name="CameraTransform_6"
                makeDefault={false}
                far={500}
                near={0.1}
                fov={30.676}
                position={[-19.359, -2.917, 15.606]}
                rotation={[0.16, -0.876, -0.791]}
              />
              <PerspectiveCamera
                name="CameraTransform_7"
                makeDefault={false}
                far={500}
                near={0.1}
                fov={30.676}
                position={[0, -2.295, 8.579]}
                rotation={[0.65, 0, 0]}
              />
              <PerspectiveCamera
                name="CameraTransform_8"
                makeDefault={false}
                far={500}
                near={0.1}
                fov={30.676}
                position={[0, -9.69, 7.444]}
                rotation={[0.518, 0, 0]}
              />
            </group>
            <group name="clayAmbient">
              <group name="omni_fore" position={[0, 0, 500]} />
              <group name="omni_bakc" position={[0, 0, -300]} />
              <group name="omnileft" position={[1000, 0, 0]} />
              <group name="ambient_1" position={[0, 0, 300]} />
            </group>
          </group>
          <group name="Materials" />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/Samsung_Galaxy_S21_Ultra_2021.glb')
